import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const convertToNextClassName = (className) => className.split(' ').map(c => styles[c]).join(' ');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navContainer}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <div className={convertToNextClassName("description text-center")}>
          <h1>Blogging With Emad</h1>
        </div>
        <br></br>
        <div className={styles.blogs}>
          <div className={styles.blog}>
            <h2>Blog Title</h2>
            <p>description</p>
          </div>
          <div className={styles.blog}>
            <h2>Blog Title</h2>
            <p>description</p>
          </div>
          <div className={styles.blog}>
            <h2>Blog Title</h2>
            <p>description</p>
          </div>
        </div>
      </main>
    </>
  )
}
